### ISSUE TITLE
Wirecard seamless woocommerce order button

### ISSUE THREAD

**Issue by methadoni** [wirecard/woocommerce-wcs#32] opened 2017-07-07 09:11 UTC
Hello, 
I activated the Checkout Seamless plugin for woocommerce and when I did that Order Button disappeared. 
Why is this happening? I'm I doing something wrong?

Thank you.

**Comment by jakubpolomsky** [comment] 2017-07-07 09:32
Hello,

we will need more informations. Versions of your woocommerce, wordpress and chosen plugin version. If you could provide us with steps how to reproduce this behavior, we would be able to fix any possible issues very quickly.

Thank you!

**Comment by methadoni** [comment] 2017-07-07 10:26
Thank you for your quick response.
 woocommerce Version 2.6.14
WordPress 4.8
chosen plugin Wirecard Checkout Seamless plugin for WooCommerce Version 1.0.0

Here are two photos 
with plugin:
![checkout_with_plugin](https://user-images.githubusercontent.com/6785846/27954250-d009384e-6317-11e7-8b46-36166ff6bc0a.png)


without plugin:
![checkout_without_plugin](https://user-images.githubusercontent.com/6785846/27954143-59033e0c-6317-11e7-80ac-8c8901a2b64e.JPG)

**Comment by jakubpolomsky** [comment] 2017-07-07 10:32
The version 1.0.0 relies on composer installation of required components of our plugin. Therefore I'd like to ask you to update your plugin version to 1.0.1 where this is no more needed. This version also fixes some possible issues during checkout. Please let me know if that solved your problem.

Thank you

**Comment by methadoni** [comment] 2017-07-07 10:39
I have Visual Composer. But I can try the update if it fixes the problem.  This [guide](https://guides.wirecard.at/shop_plugins:start)  has the vesion 1.0.0. Where i can find 1.0.1?

**Comment by jakubpolomsky** [comment] 2017-07-07 10:44
Please have a look at the [releases](https://github.com/wirecard/woocommerce-wcs/releases), you will find the 1.0.1 there.

**Comment by methadoni** [comment] 2017-07-07 10:58
release 1.0.1

"The package could not be installed. No valid plugins were found.

Plugin install failed."

**Comment by jakubpolomsky** [comment] 2017-07-07 11:07
Do you know the basic plugin structure for wordpress? You can't just upload the zip from github. You have to unpack it, open the directory and pack the contents of it. Then you can upload it via zip. Or otherwise you might just want to take the directory woocommerce-wirecard-checkout-seamless and upload it into the wp-content/plugins directory of your wordpress installation overwriting any files inside of it.

If you try to upload it via the installer of wordpress admin you will get an error saying that the plugin directory already exists. If that happens and you insist on using the wordpress installer, I suggest to uninstall and delete the "old" plugin and then upload the new repacked zip.

Regards

**Comment by jakubpolomsky** [comment] 2017-07-07 11:09
You have to unpack the zip you downloaded, open the extracted directory and pack the **contents** of the directory `woocommerce-wirecard-checkout-seamless` it. Then you can upload it via zip. Or otherwise you might just want to take the directory `woocommerce-wirecard-checkout-seamless` and upload it into the `wp-content/plugins` directory of your wordpress installation overwriting any files inside of it.

If you try to upload it via the installer of wordpress admin you will get an error saying that the plugin directory already exists. If that happens and you insist on using the wordpress installer, I suggest to uninstall and delete the "old" plugin and then upload the new repacked zip.

Regards

**Comment by methadoni** [comment] 2017-07-07 11:22
Firstly I m not very used of WordPress. I m object oriented programmer with
specialized in mobile. I haven't upload again from github plugin. Sorry my
mistake. I have delete the old one and checked the folder that is not
there. I will do what you said and try again. Thank you again for your
quick responses. I m very impressed.

**Comment by jakubpolomsky** [comment] 2017-07-10 10:58
Hello! How are you doing? Did everything work afterwards? Should you need any further assistance please let us know. I'd like to close this issue if you are satisfied.

**Comment by methadoni** [comment] 2017-07-10 12:45
Hello. Fine. I installed the plugin 1.0.1 correctly but did not fix the issue.

**Comment by jakubpolomsky** [comment] 2017-07-10 13:33
Then I need to know what template you have activated. Thank you!

**Comment by methadoni** [comment] 2017-07-11 13:11
This is the theme we are using. http://8theme.com/demo/woopress/boxed/ (live preview) with costumization. The Checkout page doesn't have a lot of custom code. It is mostly the theme with some plugins.  If you want to provide you more info let me know. Thank you.

**Comment by jakubpolomsky** [comment] 2017-07-11 13:18
I need to know the name of the template. It looks like a template which is very different to the twenty fifteen, sixteen or seventeen. Please try our plugin with one of these first and if that works, please let us know what template you are using. Thank you!

**Comment by methadoni** [comment] 2017-07-11 14:00
The name of our template is **woopress**. And the original theme is http://8theme.com/demo/woopress/boxed/  .   The problem appears to this page https://coffeebrandsdelivery.ae/checkout/.

**Comment by rinnhofer** [comment] 2017-07-14 08:25
Since it is not possible for us to test every theme for wordpress, we test our plugin with the themes which are default provided from wordpress or woocommerce. As my colleague already asked: Please try the plugin with one of these themes. If there is no error with one of these it is a problem with your theme and has to be adapted in the method payment_fields() in class "class-wirecard-gateway.php"

**Comment by methadoni** [comment] 2017-07-14 12:31
place order button is shown now with the theme twentyseventeen but there is an error. 
It seems our theme doesn't feet with your plugin but we still have errors.

![image](https://user-images.githubusercontent.com/6785846/28212270-5330dc86-68a9-11e7-9377-ac69d8757f34.png)

**Comment by rinnhofer** [comment] 2017-07-17 05:28
Looks like your configuration is not complete. Maybe you have forgotten a mandatory field. Have you filled out customerId, secret (should be set if configuration is on "production") and URL to imprint page?
If there is an error in the comunication this should be reported in your logfile too, you can find it in "wp-content/uploads/wc-logs/"

**Closed** 2017-08-14 08:08 UTC
